### PR TITLE
Bubblesort Full Ruby Project - Microverse

### PR DESCRIPTION
**Pull request by jmontanholi**
## In this simple project me and my partner practiced the use of:
  - Methods
  - Loops
  - Yield
  - Debugging
  - Variables
  - Arrays

### CODE REVIEW

**Review by smcommits — CHANGES_REQUESTED** [review]
# Status: Changes Required
## Hello, @jmontanholi and @kiranitor123! You guys have done a good job. But the algorithm that you have implemented is not actually bubble sort. 

## Required Changes

- [x]  **Please use the bubble sort algorithm to sort the collection**
Currently, you are taking one element and comparing it with every other element in the array. 
Bubble sort is a simple sorting algorithm. This sorting algorithm is a comparison-based algorithm in which each pair of adjacent elements is compared and the elements are swapped if they are not in order.

Bubble sort starts with the very first two elements, comparing them to check which one is greater.

**Consider the following array** 
[14, 33, 27, 35, 10]

In this case, value 33 is greater than 14, so it is already in sorted locations. Next, we compare 33 with 27. We find that 27 is smaller than 33 and these two values must be swapped.

The resulting array will look like: [14, 27, 33, 35, 10]

# 
### Please don't hesitate to contact me on [Slack](https://microverse-students.slack.com/team/U017N7LLZ40) if you need assistance or believe I have overlooked something and made an unfair request.

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Status: Changes Required :red_circle: 

### Hello team, great job implementing the required changes from the previous TSE. You are almost done and only have one more thing to fix:
- [x] Your bubble sort should sort the array starting from the smallest to the biggest, currently yours does the contrary for example **Bubble_sort**:
-   expected: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
                              got: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1] 
- [x] **Bubble_sort_by** needs change as well because it not returning the strings from the smallest to the biggest:
- expected: ["h", "hi", "hey", "hiya", "hello"]
            got: ["hiya", "hey", "hi", "h", "hello"]

Please fix the required changes and ask for another code review whenever you're ready

_**If you have any question related to the required changes feel free to text me on slack @GzimAsani** or just add a comment here_

HAPPY CODING :computer: :desktop_computer:

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve 
  - [x] [MANDATORY] Please use the bubble sort algorithm to sort the collection
Currently, you are taking one element and comparing it with every other element in the array.
Bubble sort is a simple sorting algorithm. This sorting algorithm is a comparison-based algorithm in which each pair of adjacent elements is compared and the elements are swapped if they are not in order. find more about it [here](https://www.tutorialspoint.com/data_structures_algorithms/bubble_sort_algorithm.htm)
  - [x] [MANDATORY] bubble_sort is not working as expected
    - Example: `bubble_sort([3, 1, 2, 5, 6, 8, 7, 10, 9, 4])`
       - Expected: `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`
       - Got: `[1, 2, 3, 5, 6, 7, 8, 9, 4, 10]`
  - [x] [MANDATORY] bubble_sort is not working as expected
    - Example: `bubble_sort_by(["hiya", "hey", "hi", "h", "hello"]) { |left, right| left.length - right.length }`
       - Expected: `["h", "hi", "hey", "hiya", "hello"]`
       - Got: `["hey", "hi", "h", "hiya", "hello"]`
  - [x] [MANDATORY] In your README,on getting started section, try to be a little more specific on how to setup and run your project locally, step by step.     
  - [x] [MANDATORY] Make sure you remove all rebugging codes before you submit.     
  

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve 
  - [x] [MANDATORY] You did not implement anything from the previous feedback. Please refer to the following screenshot if you want to get a clear picture on what I was talking about. 
    Capture17
     NOPE: your functions should be able to sort any kind of array for the first attempt.

  

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by andresporras3423 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Rolando Alvarez Faye  & João Montanholi Nunes** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the master branch
 
Keep going like this  :clap: :clap:
 
Oscar Andrés Russi Porras

**Pull request merged**
